### ISSUE TITLE
libgfortran issue

### ISSUE THREAD

**Issue by mohseniaref** [treverhines/SlipPy#1]
Hi,

I face the libgfortran error when I am trying to use Anaconda2 and Slippy
would you please guide me to solve this problem
mohseni@geomatics:~/software/SlipPy/example$ slippy 
Traceback (most recent call last):
  File "/home/mohseni/anaconda2/bin/slippy", line 5, in <module>
    import slippy.inversion
  File "/home/mohseni/anaconda2/lib/python2.7/site-packages/slippy/inversion.py", line 10, in <module>
    import scipy.optimize
  File "/home/mohseni/anaconda2/lib/python2.7/site-packages/scipy/optimize/__init__.py", line 221, in <module>
    from .optimize import *
  File "/home/mohseni/anaconda2/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "/home/mohseni/anaconda2/lib/python2.7/site-packages/scipy/optimize/linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory

**Comment by treverhines** [comment]
Do you have gfortran on your computer?  If you do then this is going to be an issue with F2PY. F2PY is used to make a python wrapper for the Okada92 fortran program. Unfortunately F2PY is a bit of a black box to me and I cannot really help you out with it.
 
I have seen this same issue while trying to get slippy to work on Macs. I eventually gave up on trying to figure out what was wrong, and I implemented a cython version of Okada92. You can use the cython version by rebuilding slippy with the command 
`python setup_nofortran.py install`

**Comment by lcx366** [comment]
Hi,

Can you explain what 'penalty' means in the fault geometry parameters within Slippy or give some references on it? I have browsed lots of information involved in fault geometry parameters, however noting was found with respect to 'penalty'. 

Thanks

**Comment by treverhines** [comment]
"penalty" controls the roughness of the slip solution. A larger value gives more weight to the regularization constraint that the Laplacian of the slip solution is zero.
